name: "Validate Gradle Wrapper"
on:
  push:
    branches:
      - main
      - release/**

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
